version: '3'

services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - direct

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"password\""]
    volumes:
      - redis:/data/redis
    networks:
      - direct

  botpress:
    image: botpress/server:v12_30_7
    ports:
      - '3001:3000'
    depends_on:
      - postgres
    volumes:
      - botpress:/botpress/data
    networks:
      - direct

  chatwoot:
    image: chatwoot/chatwoot:v2.13.1
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=Testing1234
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=chatwoot
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=password
      - RAILS_DEFAULT_URL=http://localhost:3003
      - FRONTEND_URL=http://localhost:3003
    ports:
      - '3003:3000'
    depends_on:
      - postgres
      - redis
      - bridge
    command: sh -c "bundle exec rails db:chatwoot_prepare; bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - chatwoot:/app/storage
    networks:
      - direct


  chatwoot-sidekiq:
    image: chatwoot/chatwoot:v2.13.1
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=Testing1234
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=chatwoot
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=password
    depends_on:
      - postgres
      - redis
      - chatwoot
    command: sh -c "bundle exec sidekiq -C config/sidekiq.yml"
    networks:
      - direct

  bridge:
    build: .
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=Testing1234
      - BOTPRESS_ENDPOINT=http://botpress:3000
      - BOTPRESS_BOT_ID=chatwoot
      - CHATWOOT_ENDPOINT=http://chatwoot:3000
      - CHATWOOT_BOT_TOKEN=c7L7vNBvokvCA4Wpzrvxy9Yv
      - CHATWOOT_ALLOWED_STATUSES=open,pending
    ports:
      - '3002:3000'
    depends_on:
      - botpress
    volumes:
      - .:/app
    command: rails s -p 3000 -b 0.0.0.0
    networks:
      - direct


volumes:
  postgres:
  redis:
  botpress:
  chatwoot:

networks:
  direct:
    driver: bridge
